version: "3.6"

services:
  database:
    container_name: "mock_database"
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    restart: unless-stopped
